sudo: false
env:
  global:
    - secure: "fuGzaeyX0ar31vzAxYEpyN4wNposH6XlG3Eby6uM2TbHDgkfFpH3n4q19P7E96QYBLZCW9/teViXJbs0HVhGBCrEF5nuk40Y/JWJSPAg2/1dpGCRNRLDFtLdtNBbd8PQyGqp1PXWA9jc/zU9bmUgppmqrAlbThmKBgLZKC0cgE7hV4YWU1j+TwKaF4QjwVDqWU9UaLdZV/kcMLexBu48NQVgZPjwKpFXHeM/ZuUqBTlMQrl7FXrS/9pnvxg0sPu8VAMK1yxOWEhro67orLq37DQSLi6QLE+ltSL4EeLFAyBk166aapDsGUqHGfD8nFfYahchoVXfRkOALSYGMxDFBaFVsNrUZ4vP9mzSNU1ozC8XhmG/zm2ol32mtis6JnuAXtJ4kJBTv+ccanb+h1+1GgejqMX37Q+B978qQ6RMWW7bNzrM++sOflOwWXFZ16UPE/5SqVzxEv05tS/mygwG6O/fI+IUG6OYc7+FdmNjwSmuo2D17r46oHmpAUV0hc7QUmaFIFR2eQtbFsFNfxRnB/k+h86RLCZeECkywgoWOmd1Vu79pN1DIIkdl8hdOQbiYkHa5xE3uvNov/WGOpivB8xEA8ygtLPs1e4J6Wl3h8i8ZolbrCTJa12bNVTuNvqbdgRD9vOGP6ilYY8CbPzAIc2Fgjbkgd0ZK439ae2cnec="
    - secure: "pK6XHI298lbEGEcytxxKPczPAfjuP8PN9jZ4E26n1BEi+SFVI3vChREQXQx2bRcZBuqeS4wlAQFxhIuq3EiGAJCvS5hiSu/2Ov7EEksoTJMPeguB47b1DCNL01sHJUxKFao6k5lBoew80pP5W7hgVMKFFnFwhEYcIJGVUoO8mkcC3nLJ/IHymWv9PBw01dv5VRQRlxcpBzTYt4jITEnaqafVG2BN4aaaiDsntQ50gynOcwTFEIj/JbVPIg6ylqhjXc8+Pw1CfGnqtB/fCz6CNz/jJ53YgIEpgMrXpM2o7gVMzDk6SmOKHDvECyqk6S/jDkAE7AJGocA1/8TlV8Q5Bg7WXcQ73cRYq3DsSUixn+9EVwW4EghuX+gEom7O49ZD5PuGYVNRTlrpub5d7g8kVSxjGBbnojGgw+bNCBSfpsbEkoZ8gPsBs4yuVCDOsEEDuYTBo882tb1VjKTxI8h4gnRhs6GQQ57YXsMzGOFvyXh6LgiAnQ/wjG7E3UA7aw/0tMszapW600X0RstYM+gYEMU4hQhwi8EI7/dbTzhR+yijoFkvwWjMJdtYGvb/BtHW8lk+Y2XYavDAfjibwuwDfd4RBuiGRZf4pEdCY3wviJg1eIkbbXuWC/4Btum89gIH24ywzye5HY1+HCG6Dy2k87akes+mCCSp9nSNdKQrb0g="

language: generic
matrix:
  include:
    - os: linux
      env: PYTHON="3.5"

    - os: linux
      env: PYTHON="3.6"

    - os: osx
      env: PYTHON="3.5"

    - os: osx
      env: PYTHON="3.6"

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels bryanwweber
  - conda config --append channels conda-forge
  - conda update -q --all
  - if [[ -z "$TRAVIS_TAG" ]]; then
      conda create -q -n test-environment python=$PYTHON pytest pytest-cov coolprop pint;
      source activate test-environment;
    else
      conda install -q conda-build anaconda-client;
    fi
  - conda info -a
  - conda list

script:
  - if [[ -z "$TRAVIS_TAG" ]]; then
      python setup.py test;
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$PYTHON" == "3.5" ]]; then
        conda install -q sphinx doctr coolprop pint;
        python setup.py install;
        set -e;
        cd docs;
        make html SPHINXOPTS="-W";
        cd ..;
        doctr deploy --gh-pages-docs .;
        set +e;
      fi
    else
      conda build conda.recipe --python=${PYTHON};
      anaconda -t $ANACONDA_TOKEN upload $HOME/miniconda/conda-bld/*/thermostate*.tar.bz2
    fi

after_success:
  - if [[ -z "$TRAVIS_TAG" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi
