version: 1.0.{build}
skip_tags: true
environment:
  matrix:
    - PYTHON_LOC: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.5"

    - PYTHON_LOC: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda config --append channels bryanwweber
  - cmd: conda config --append channels conda-forge
  - cmd: conda update --all -q
  - cmd: conda create -q -n test-environment python=%PYTHON_VERSION% pytest pytest-cov coolprop pint
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat test-environment
  - cmd: conda info -a
  - cmd: conda list

build_script:
  - cmd: python setup.py test
