version: 1.0.{build}
skip_tags: true

environment:
  PYTHON_LOC: "C:\\Miniconda36-x64"

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda config --append channels bryanwweber
  - cmd: conda config --append channels conda-forge
  - cmd: conda update --all -q
  - cmd: conda create -q -n py35 python=3.5 pytest pytest-cov coolprop pint codecov
  - cmd: conda create -q -n py36 python=3.6 pytest pytest-cov coolprop pint codecov
  - cmd: conda info -a
  - cmd: conda list

build_script:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat py35
  - cmd: python setup.py test
  - cmd: codecov
  - cmd: rmdir /s /q thermostate.egg-info
  - cmd: rmdir /s /q .eggs
  - cmd: rm .coverage
  - cmd: call %PYTHON_LOC%\Scripts\\activate.bat py36
  - cmd: python setup.py test
  - cmd: codecov
