{% set data = load_setup_py_data() %}

package:
  name: thermostate
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python >=3.4,{{PY_VER}}*
    - setuptools

  run:
    - python {{PY_VER}}*
    - coolprop >=6.1.0
    - pint >=0.7.2

test:
  imports:
    - thermostate

  requires:
    - pytest >=3.0.0
    - pytest-cov >=2.3.1

  commands:
    - pytest -vv --pyargs thermostate

about:
  home: https://github.com/bryanwweber/UConnRCMPy
  license: MIT
  license_file: LICENSE.md
